#!/bin/sh

cd ..

JSONCPP_FLAGS="-DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DJSONCPP_WITH_TESTS=OFF -DJSONCPP_WITH_POST_BUILD_UNITTEST=OFF -DJSONCPP_WITH_WARNING_AS_ERROR=OFF -DJSONCPP_WITH_PKGCONFIG_SUPPORT=OFF -DJSONCPP_WITH_CMAKE_PACKAGE=OFF -DJSONCPP_WITH_EXAMPLE=OFF -DJSONCPP_WITH_DOCUMENTATION=OFF -DJSONCPP_WITH_CMAKE_CONFIG=OFF -DJSONCPP_WITH_PKGCONFIG_SUPPORT=OFF -DJSONCPP_WITH_CMAKE_PACKAGE=OFF -DJSONCPP_WITH_PKGCONFIG_SUPPORT=OFF -DJSONCPP_WITH_CMAKE_CONFIG=OFF -DJSONCPP_WITH_EXAMPLE=OFF -DJSONCPP_WITH_DOCUMENTATION=OFF -DJSONCPP_WITH_WARNING_AS_ERROR=OFF -DJSONCPP_WITH_POST_BUILD_UNITTEST=OFF -DJSONCPP_WITH_TESTS=OFF"

## jsoncpp
echo "Building jsoncpp"

cd jsoncpp
rm -rf build
mkdir build
cd build
cmake $JSONCPP_FLAGS ..
if [ $? -ne 0 ]; then
    echo "Failed to configure jsoncpp; see above for details"
    exit 1
fi
make
if [ $? -ne 0 ]; then
    echo "Failed to build jsoncpp; see above for details"
    exit 1
fi
cd ../..

echo "Done"
